/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/files`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/svgContants`; params?: Router.UnknownInputParams; } | { pathname: `/visualization`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/component/CommonHeader`; params?: Router.UnknownInputParams; } | { pathname: `/component/ErrorPopup`; params?: Router.UnknownInputParams; } | { pathname: `/component/TechnicalSupport`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/files`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/svgContants`; params?: Router.UnknownOutputParams; } | { pathname: `/visualization`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/component/CommonHeader`; params?: Router.UnknownOutputParams; } | { pathname: `/component/ErrorPopup`; params?: Router.UnknownOutputParams; } | { pathname: `/component/TechnicalSupport`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/files${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/svgContants${`?${string}` | `#${string}` | ''}` | `/visualization${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/component/CommonHeader${`?${string}` | `#${string}` | ''}` | `/component/ErrorPopup${`?${string}` | `#${string}` | ''}` | `/component/TechnicalSupport${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/files`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/svgContants`; params?: Router.UnknownInputParams; } | { pathname: `/visualization`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/component/CommonHeader`; params?: Router.UnknownInputParams; } | { pathname: `/component/ErrorPopup`; params?: Router.UnknownInputParams; } | { pathname: `/component/TechnicalSupport`; params?: Router.UnknownInputParams; };
    }
  }
}
